language: node_js
node_js:
  - 9
addons:
  apt:
    packages:
      - sshpass

install:
  - cd app
  - npm install
before_script:
  - npm install -g gulp-cli  
script:
  - gulp
  - cd application/config
  - cp database.sample.php database.php
  - sed -i "78s 127.0.0.1 $D_DATABASESERVER " database.php
  - sed -i "79s usernametoreplace $D_USERNAME " database.php
  - sed -i "80s passwordtoreplace $D_DBPASSWORD " database.php
  - sed -i "81s databasetoreplace $D_DATABASE " database.php
  - cp config.sample.php config.php
  - sed -i "26s replace $D_URLFIRSTHALF$TRAVIS_PULL_REQUEST_BRANCH/app/ " config.php
after_success:
  - cd ../..
  - export SSHPASS=$D_PASSWORD
  - echo "Starting upload... (escaped quotes)"
  - "sshpass -e ssh $D_USERNAME@$D_SERVER 'mkdir -p '\"$D_PATH$TRAVIS_PULL_REQUEST_BRANCH\"'/app/'"
  - sshpass -e scp -o StrictHostKeyChecking=no -r static/ application/ system/ index.php $D_USERNAME@$D_SERVER:$D_PATH$TRAVIS_PULL_REQUEST_BRANCH/app/
