language: node_js
addons:
    apt:
        packages:
            - sshpass

install:
  - "cd app"
  - "npm install"
before_script:
  - npm install -g gulp-cli  
script:
  - "gulp"
after_success:
  - "export SSHPASS=$d_ps"
  - "sshpass -e scp -r static/ $d_u@$d_s:$d_p"
