language: node_js
node_js:
  - "9"
addons:
    apt:
        packages:
            - sshpass

install:
  - "cd app"
  - "npm install"
before_script:
  - npm install -g gulp-cli  
script:
  - "gulp"
after_success:
  - "export SSHPASS=$D_PASSWORD"
  - "sshpass -e scp -r -o StrictHostKeyChecking=no static/ $D_USERNAME@$D_SERVER:$D_PATH -o StrictHostKeyChecking=no"
